export const FETCH_DRIVERS = "FETCH_DRIVERS";
export const FETCH_DRIVERS_SUCCESS = "FETCH_DRIVERS_SUCCESS";
export const FETCH_DRIVERS_FAIL = "FETCH_DRIVERS_FAIL";

export const FETCH_CARS = "FETCH_CARS";
export const FETCH_CARS_SUCCESS = "FETCH_CARS_SUCCESS";
export const FETCH_CARS_FAIL = "FETCH_CARS_FAIL";

export const FETCH_INCIDENTS = "FETCH_INCIDENTS";
export const FETCH_INCIDENTS_SUCCESS = "FETCH_INCIDENTS_SUCCESS";
export const FETCH_INCIDENTS_FAIL = "FETCH_INCIDENTS_FAIL";

export const FETCH_NEW_INCIDENTS = "FETCH_NEW_INCIDENTS";
export const FETCH_NEW_INCIDENTS_SUCCESS = "FETCH_NEW_INCIDENTS_SUCCESS";
export const FETCH_NEW_INCIDENTS_FAIL = "FETCH_NEW_INCIDENTS_FAIL";

export const FETCH_INCIDENT = "FETCH_INCIDENT";
export const FETCH_INCIDENT_SUCCESS = "FETCH_INCIDENT_SUCCESS";
export const FETCH_INCIDENT_FAIL = "FETCH_INCIDENT_FAIL";
